# Generated by Django 4.2.7 on 2023-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('delete_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
